name: Deploy to Azure

on:
  push:
    branches:
      - main  # or the branch you want to trigger the deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code from the repository
    - name: 'Checkout GitHub Actions'
      uses: actions/checkout@v3

    # Login to Azure using Azure/login
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Run the deployment script or commands
    - name: 'Run deployment'
      run: |
        az group create --name <ResourceGroup> --location <Location>
        az deployment group create --resource-group <ResourceGroup> --template-file <YourTemplate>.json
