name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Actions'
        uses: actions/checkout@v3

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # JSON object with client-id, client-secret, tenant-id, subscription-id

      - name: 'Run deployment'
        run: |
          az group create --name <ResourceGroup> --location <Location>
          az deployment group create --resource-group <ResourceGroup> --template-file <YourTemplate>.json
