name: Deploy to Azure

on:
  push:
    branches:
      - main  # Or your branch to trigger the deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code from the repository
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # JSON object with client-id, client-secret, tenant-id, subscription-id

    # Run deployment commands
    - name: 'Run deployment'
      run: |
        az group create --name location-backend_group --location "Central US"
        az deployment group create --resource-group location-backend_group --template-file myTemplate.json

permissions:
  id-token: write
