name: Deploy to Azure

on:
  push:
    branches:
      - main  # Or your branch to trigger the deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code from the repository
    - name: 'Checkout GitHub Actions'
      uses: actions/checkout@v3

    # Login to Azure using Azure/login
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        auth-type: SERVICE_PRINCIPAL

    # Run deployment commands
    - name: 'Run deployment'
      run: |
        az group create --name location-backend_group --location "Central US"
        az deployment group create --resource-group location-backend_group --template-file myTemplate.json

permissions:
  id-token: write
